language: java
jdk:
  - oraclejdk8

before_deploy:
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in deploy/travis-key.enc -out deploy/travis-key -d
  - chmod 700 deploy/travis-key

deploy:
  skip_cleanup: true
  provider: script
  script: deploy/deploy.sh
  on:
    branch: add_ssh_key_to_travis

after_deploy:
  rm deploy/travis-key
